### ISSUE TITLE
Name of File representing this book is more than stupid!

### ISSUE THREAD

**Issue by pdfkungfoo** [ElektraInitiative/book#1]
This is my pet peef which haunts me almost every day when I'm looking for PDF files on the Internets... Finally now I decided to blow off my surplus pressure. Sorry if it hits YOU only for now (many others would also deserve it), and sorry if you feel innocent.

I don't know how often it happened in my early internet life that I downloaded a PDF, DOC, XLX or other document only to find that the download had simply overwritten another, completely un-related file. It must have been more than a dozen times. Took some time to make it a habit to check for the filename, and then decide about new one on the fly before saving it to disk.

C'mon, people! Characters are free. Bytes to store longer, meaningful file names are almost free. File systems no longer suffer from a 8+3 limitation. You could easily use document filenames which are self-describing about their content, their publisher, the version, language and release date of the ouvre.

Why use "report.doc", "table.xlx", "notes.txt", "movie.mp4", "test.config" or "book.pdf" for ANYTHING that someone releases upon humanity or that you keep on your local disk privately? Are you just too lazy? Don't you think about how your laziness causes you more work later, because you can't tell your own "myfile.ext" from your sister's "myfile.ext"? Don't you have any thoughts for your neighbourly hackers who want clearly distinct names for the files they have to handle?

Don't you want your publication be *RECOGNIZED* by search engines, or humans browsing websites, or bots scanning through file systems? Filenames are the most obvious and easy to use ELEMENTARY metadata which *COULD* be made use of....

Have you ever wondered why in shops of all types the products are not labelled the same way, and don't use the same cardbox types, material and color, so every time you want to buy something you'd have to look inside many packagings first before you find what you look for? And at home, of course, you'd be clever enough to stock the stuff in clearly distinguishable containers, after un-packing your shop lootings...

So, please, think of a better name than "book.pdf". How about something simple, like "electra-book-2017-december-markus-raab.pdf"? Let me know if you don't have enough storage for these extra letters. I'll shed some tears then...

----

*How can I even start off with even the most basic trust in the sanity and thoughtfulness of elektra developers if the first thing I encounter when looking at their project is such a stupidly careless naming for something which may be THE showcase document about their efforts???*

**Comment by markus2330** [comment]
Thank you for your input. My browser downloads to randomly generated tmp-folders (if I do not want to keep the file. If I want to keep it, I give the file a name myself).

Your use case nevertheless makes sense, so I renamed the file. I also moved it outside of this repo because binaries and sources should not be intermixed. For your convenience, you can [read the book here](https://www.libelektra.org/ftp/elektra/publications/raab2017context.pdf).

> How can I even start off with even the most basic trust in the sanity and thoughtfulness of elektra developers if the first thing I encounter when looking at their project is such a stupidly careless naming for something which may be THE showcase document about their efforts???

I take the last part as compliment. For the first part, I did not feel there was an ambiguity, because:

- it is the only book I have written
- the only book about Elektra
- the only book within this git repo

I do not see a break in trust because of short names ("Elektra" itself is arguable short and has many collisions). It is not like we create zip files, which unpacks at your root and overwrites important files. (Here I would see a clear violation of trust). Browsers that overwrite files without asking are broken. There is no FNS for unique file names in the Internet. (Bittorrent with its hashes maybe is. But I thought the file is too small to be useful for bittorrent distribution.)

I hope you nevertheless consider Elektra for your projects 👍

**Comment by pdfkungfoo** [comment]
I take the last part as compliment.
> *"I take the last part as compliment."*

You may well do so.  That was the (hidden) intention. 👍 

> *"For the first part, I did not feel there was an ambiguity, because:
>
> * *it is the only book I have written"*

Your perspective is too narrow and ego-centric here:

* You're not the only one wanting to read (?!? -- rather *"work through"*) the book.
* This book will be saved to disks alongside other PDF files.
* Even if not, it will be downloaded by others and offered within a collection of documents. Think "FOSDEM". (It's called "book.pdf" in that context too. WTF?!? Also, the respective slides are carrying a similarly stupid filename, can't remember ATM, which. Maybe "slides.pdf" or maybe "elektra.pdf"? The second is only slightly better than the first....)

> * *"the only book about Elektra*
> * *the only book within this git repo*"

Don't be so stubborn with your arguments here  :-)

> *"Browsers that overwrite files without asking are broken."*

I didn't say it still happens to me. I referred to *"my early internet life"* if you want to look it up again. However, finding a list of "book.pdf", "book (1).pdf", "book (2).pdf", ... files in my Downloads folder is still not the best I'm hoping for.

> *"There is no FNS for unique file names in the Internet."*

No, there isn't. But there's something called "common sense". Which sometimes is wiser than expected.

> *"I hope you nevertheless consider Elektra for your projects"*

Oh, I certainly will (even though I'm not what you or I myself would rate as a "developer")! 

Unfortunately I will not be able to attend FOSDEM. If I could, your talk would definitely be *THE ONE* which I most urgently would try to attend, even if it was scheduled at an early morning hour.

I am (or rather *was*) aware of Elektra since more than 12 years ago already, when I was in loose contact with Avi Alkalay. I even tried to raise awareness for the Elektra efforts within the KDE community (where, at the time, I contributed bits and pieces of documentation about KDEPrint). Due to some health problems I got knocked off from quite some of my open source activities for a number of years. I had forgotten about Elektra, until very recently, when I again became aware of it and was happy to learn it was still alive and kicking!

So thanks to you and your work on it for pushing it to the level of maturity it has now.

And thank you *here* for your stubbornness in persuing the Elektra goals, which probably helped a lot to keep the project on track 👍  🥇 .

As said before, you were a rather random victim for my rant. There are a lot more people out there, not just in IT, who would deserve the same "abuse". (Just this morning I downloaded a file from a financial institution which was named "yearly_report.pdf" (my translation -- the original was "jahres_Bericht.pdf"...), where I had to manually insert "2016" and "$institutionname" into the file name...)

Good that you took it so lightly :-)
Best of luck and success for your FOSDEM talk and for Elektra in general!

----

<sup>BTW, it was not my intention to have a *longer* name for the book. Rather a *self-explanatory* name...</sup>
<sup>Also, naming the ***same*** thing *context-aware-configuration-book.pdf* at one place and *raab2017context.pdf* at another is not exactly a proof of having grokked the spirit of my above ranting... I cannot believe such blunders being committed by someone who works tirelessly for many years to streamline chaotic configuration methods!</sup>

**Comment by markus2330** [comment]
> This book will be saved to disks alongside other PDF files.

I am looking forward to it.

> Think "FOSDEM". (It's called "book.pdf" in that context too.

It is maybe the only book within the FOSDEM talks, too. But thank you for the tip, I renamed the files for FOSDEM, too.

> No, there isn't. But there's something called "common sense". Which sometimes is wiser than expected.

Yes, it is important to give good names. But I am afraid that is hardly practiced and unfortunately not "common sense". Otherwise you would not have the problem with book.pdf (333) 😄 

> Unfortunately I will not be able to attend FOSDEM. If I could, your talk would definitely be THE ONE which I most urgently would try to attend, even if it was scheduled at an early morning hour.

Thank you. Hopefully the stream/video archive will work. And let us hope the video will have a great name 😄

> context-aware-configuration-book.pdf

... was only a test if symlinks work on GitHub. Unfortunately they do not. (In the raw download you get the text of the content of the symlink). Also the file name depends on where it is stored. Where it is now, there is the name convention `<name><year><first word>.pdf`.

> I cannot believe such blunders being committed by someone who works tirelessly for many years to streamline chaotic configuration methods!

One of the outcomes (as published in the book) it is unrealistic to enforce a common tautology/naming scheme. So instead we propose to derive the configuration settings from other configuration settings.

So an application simply gets "/sw/org/myapp/#0/current/format/paper" and does not care where it will get this configuration setting from. If /etc/papersize happens to contain the paper format that is relevant for myapp, the admin can create a kind-of-symbolic-link so that myapp will use /etc/papersize when requesting "/sw/org/myapp/#0/current/format/paper" (next to other namespaces/overrides and so on, see section "Specification" [here]( https://www.libelektra.org/tutorials/integration-of-your-application)). If you are interested in details, please open an issue (with question tag) in the main repo. We are getting offtopic here, thus I will close the issue.

Thank you for your encouraging feedback.

**Comment by pdfkungfoo** [comment]
Closing this "issue" now is Ok for me. 😄

And thanks a bunch for the explanations in your last paragraph. I learned a bit from them. (Admittedly, I haven't yet had the time to deep-dive into Elektra, nor read more than a few intro pages of your book...)

----
<sup>(BTW, I insist to call something(s) "common sense" for myself even if they are not (yet) THAT common...)</sup>
